const PRODUCTS = [
  {
    id: 1,
    name: "Alumni Heritage Hoodie",
    category: "Apparel",
    price: 7800,
    subtitle: "Heavyweight cotton blend",
    code: "AH",
    description: "A premium alumni hoodie with structured fit for campus events and everyday wear.",
    details: ["80% cotton / 20% polyester", "Embossed DBHS crest", "Unisex fit", "Machine washable"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviewCount: 42
  },
  {
    id: 2,
    name: "DBHS Crest Tee",
    category: "Apparel",
    price: 4200,
    subtitle: "Soft ring-spun cotton",
    code: "CT",
    description: "Classic alumni t-shirt with a lightweight feel and clean crest print.",
    details: ["100% ring-spun cotton", "Pre-shrunk fabric", "Crew neck", "Soft-touch print"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    reviewCount: 30
  },
  {
    id: 3,
    name: "Reunion Windbreaker",
    category: "Apparel",
    price: 8600,
    subtitle: "Water-resistant shell",
    code: "RW",
    description: "A lightweight layer designed for reunion weekends and unpredictable weather.",
    details: ["Water-resistant outer shell", "Packable hood", "Zip pockets", "Relaxed fit"],
    sizes: ["M", "L", "XL"],
    rating: 4.6,
    reviewCount: 25
  },
  {
    id: 4,
    name: "Blue Crest Cap",
    category: "Accessories",
    price: 3300,
    subtitle: "Adjustable back strap",
    code: "BC",
    description: "Everyday cap featuring stitched alumni crest and breathable construction.",
    details: ["Six-panel construction", "Adjustable closure", "Breathable eyelets", "Curved brim"],
    sizes: ["One Size"],
    rating: 4.4,
    reviewCount: 19
  },
  {
    id: 5,
    name: "Legacy Tote",
    category: "Accessories",
    price: 3900,
    subtitle: "Reinforced canvas body",
    code: "LT",
    description: "Durable tote for books, groceries, and alumni meetups.",
    details: ["Heavy canvas", "Reinforced handles", "Inner pocket", "Flat base"],
    sizes: ["One Size"],
    rating: 4.5,
    reviewCount: 17
  },
  {
    id: 6,
    name: "Alumni Steel Bottle",
    category: "Drinkware",
    price: 3500,
    subtitle: "Double-wall insulated",
    code: "SB",
    description: "Keeps drinks hot or cold through long classes and event days.",
    details: ["Stainless steel", "Leak-resistant lid", "BPA-free", "500ml capacity"],
    sizes: ["500ml"],
    rating: 4.8,
    reviewCount: 36
  },
  {
    id: 7,
    name: "Class Reunion Mug",
    category: "Drinkware",
    price: 2900,
    subtitle: "Gloss ceramic finish",
    code: "RM",
    description: "Commemorative mug built for reunion keepsakes and daily coffee routines.",
    details: ["Ceramic body", "Dishwasher safe", "Printed alumni text", "Classic handle"],
    sizes: ["12oz"],
    rating: 4.3,
    reviewCount: 14
  },
  {
    id: 8,
    name: "Signature Lanyard",
    category: "Accessories",
    price: 1800,
    subtitle: "Blue-white woven strap",
    code: "SL",
    description: "A clean ID lanyard for alumni functions and school visits.",
    details: ["Woven strap", "Safety breakaway", "Metal hook", "Soft-touch finish"],
    sizes: ["One Size"],
    rating: 4.2,
    reviewCount: 12
  },
  {
    id: 9,
    name: "Quarter Zip Top",
    category: "Apparel",
    price: 9200,
    subtitle: "Athletic performance fabric",
    code: "QZ",
    description: "Performance quarter zip for cool mornings and active alumni events.",
    details: ["Moisture-wicking fabric", "Stand collar", "Stretch cuffs", "Athletic cut"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviewCount: 22
  },
  {
    id: 10,
    name: "Weekend Duffel",
    category: "Accessories",
    price: 7400,
    subtitle: "Travel-ready alumni carry",
    code: "WD",
    description: "Spacious duffel for weekend trips, tournaments, and reunion travel.",
    details: ["Large main compartment", "Shoulder strap", "Side pocket", "Durable base"],
    sizes: ["One Size"],
    rating: 4.6,
    reviewCount: 20
  }
];
