-- Run this in Supabase SQL Editor

create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.merch_products (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text,
  category text not null default 'General',
  code text,
  description text,
  details text[] not null default '{}'::text[],
  sizes text[] not null default '{}'::text[],
  rating numeric(3,2) not null default 4.7,
  review_count int not null default 24,
  price_jmd numeric(12,2) not null check (price_jmd >= 0),
  stock_qty int not null default 0 check (stock_qty >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.merch_orders (
  id bigint generated by default as identity primary key,
  member_email text not null,
  subtotal_jmd numeric(12,2) not null check (subtotal_jmd >= 0),
  shipping_jmd numeric(12,2) not null check (shipping_jmd >= 0),
  total_jmd numeric(12,2) not null check (total_jmd >= 0),
  status text not null default 'new' check (status in ('new', 'processing', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.merch_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.merch_orders(id) on delete cascade,
  product_name text not null,
  product_code text,
  quantity int not null check (quantity > 0),
  unit_price_jmd numeric(12,2) not null check (unit_price_jmd >= 0),
  line_total_jmd numeric(12,2) not null check (line_total_jmd >= 0)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_merch_products_updated_at on public.merch_products;
create trigger trg_merch_products_updated_at
before update on public.merch_products
for each row
execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.merch_products enable row level security;
alter table public.merch_orders enable row level security;
alter table public.merch_order_items enable row level security;

-- Admin users table

drop policy if exists "admin_users_select_admins" on public.admin_users;
create policy "admin_users_select_admins"
on public.admin_users
for select
to authenticated
using (exists (
  select 1 from public.admin_users au where au.email = auth.email()
));

-- Products policies

drop policy if exists "products_select_authenticated" on public.merch_products;
create policy "products_select_authenticated"
on public.merch_products
for select
to authenticated
using (true);

drop policy if exists "products_admin_insert" on public.merch_products;
create policy "products_admin_insert"
on public.merch_products
for insert
to authenticated
with check (exists (
  select 1 from public.admin_users au where au.email = auth.email()
));

drop policy if exists "products_admin_update" on public.merch_products;
create policy "products_admin_update"
on public.merch_products
for update
to authenticated
using (exists (
  select 1 from public.admin_users au where au.email = auth.email()
))
with check (exists (
  select 1 from public.admin_users au where au.email = auth.email()
));

drop policy if exists "products_admin_delete" on public.merch_products;
create policy "products_admin_delete"
on public.merch_products
for delete
to authenticated
using (exists (
  select 1 from public.admin_users au where au.email = auth.email()
));

-- Orders policies

drop policy if exists "orders_insert_own" on public.merch_orders;
create policy "orders_insert_own"
on public.merch_orders
for insert
to authenticated
with check (member_email = auth.email());

drop policy if exists "orders_select_own_or_admin" on public.merch_orders;
create policy "orders_select_own_or_admin"
on public.merch_orders
for select
to authenticated
using (
  member_email = auth.email()
  or exists (select 1 from public.admin_users au where au.email = auth.email())
);

drop policy if exists "orders_admin_update" on public.merch_orders;
create policy "orders_admin_update"
on public.merch_orders
for update
to authenticated
using (exists (
  select 1 from public.admin_users au where au.email = auth.email()
))
with check (exists (
  select 1 from public.admin_users au where au.email = auth.email()
));

-- Order items policies

drop policy if exists "items_insert_with_owned_order" on public.merch_order_items;
create policy "items_insert_with_owned_order"
on public.merch_order_items
for insert
to authenticated
with check (exists (
  select 1 from public.merch_orders mo
  where mo.id = merch_order_items.order_id
    and mo.member_email = auth.email()
));

drop policy if exists "items_select_own_or_admin" on public.merch_order_items;
create policy "items_select_own_or_admin"
on public.merch_order_items
for select
to authenticated
using (
  exists (
    select 1 from public.merch_orders mo
    where mo.id = merch_order_items.order_id
      and (
        mo.member_email = auth.email()
        or exists (select 1 from public.admin_users au where au.email = auth.email())
      )
  )
);
