-- Run this in Supabase SQL Editor

create table if not exists public.alumni_dues_payments (
  id bigint generated by default as identity primary key,
  member_email text not null,
  amount_jmd numeric(12,2) not null check (amount_jmd > 0),
  region text not null check (region in ('jamaica', 'us', 'uk')),
  status text not null default 'paid',
  created_at timestamptz not null default now()
);

alter table public.alumni_dues_payments enable row level security;

drop policy if exists "dues_insert_authenticated" on public.alumni_dues_payments;
create policy "dues_insert_authenticated"
on public.alumni_dues_payments
for insert
to authenticated
with check (member_email = auth.email());

drop policy if exists "dues_select_own" on public.alumni_dues_payments;
create policy "dues_select_own"
on public.alumni_dues_payments
for select
to authenticated
using (member_email = auth.email());